shopware:
  feature:
    flags:
      - name: v6.5.0.0
        default: true
        major: true
        toggleable: false
      - name: v6.6.0.0
        default: true
        major: true
        toggleable: false
      - name: v6.7.0.0
        default: false
        major: true
        toggleable: false
      - name: DISABLE_VUE_COMPAT
        default: false
        major: true
        toggleable: false
      - name: ACCESSIBILITY_TWEAKS
        default: false
        major: true
        toggleable: true
        description: "Accessibility tweaks (highly recommended)\nAccessibility improvements can alter the HTML and CSS structure of the template.\nThe accessibility improvements will be standard as of v6.7.0"
      - name: ADMIN_VITE
        default: false
        major: false
        toggleable: false
        description: "Experimental! Uses Vite instead of webpack to built and serve the administration. Plugins are not yet supported!"
      - name: TELEMETRY_METRICS
        default: false
        major: false
        toggleable: true
        description: "Experimental! Enable OpenTelemetry metrics"
