parameters:
    messenger.default_transport_name: 'default'

framework:
    esi: true
    trusted_hosts: ~
    fragments: ~
    assets: ~
    session:
        handler_id: ~
        cookie_secure: 'auto'
        storage_factory_id: session.storage.factory.native
    serializer: { enabled: true }
    secret: "%env(APP_SECRET)%"
    validation:
        enable_annotations: true
    default_locale:  en_GB
    http_method_override: true
    mailer:
        message_bus: false
    php_errors:
        log: true
    cache:
        prefix_seed: "%kernel.cache.hash%"
        app: cache.adapter.filesystem
        pools:
            cache.object:
                default_lifetime: 10800
                adapter: cache.app
                tags: cache.tags
            cache.http:
                default_lifetime: 10800
                adapter: cache.app
                tags: cache.tags
            cache.tags:
                adapter: cache.app
    messenger:
        transports:
            default:
                dsn: "enqueue://default?receiveTimeout=100"
        default_bus: messenger.bus.shopware
        buses:
            messenger.bus.shopware:
                middleware:
                    - Shopware\Core\Framework\MessageQueue\Middleware\RetryMiddleware

sensio_framework_extra:
    router:
        annotations: false
