name: PHP Lint

on:
    push:
      branches:
          - trunk
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "PHP Analyse"
    container: shopware/development:7.4-composer-2

    steps:
    - name: Clone platform
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Install Shopware
      run: |
        composer install

    - name: Check Code
      run: |
        composer run ecs -- --no-progress-bar
        composer run phpstan -- --error-format=gitlab --no-progress | tee phpstan-report.json
        composer run lint:changelog
        composer run lint:snippets
        git remote add bc-checker-upstream https://github.com/shopware/platform.git
        git fetch bc-checker-upstream
        composer run bc-check
