name: PHP analysis

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DEVELOPMENT_BRANCH: 6.2-BoostDay

    steps:
    - name: Clone development
      run: git clone -b $DEVELOPMENT_BRANCH https://github.com/shopware/development.git && cd development && rm -rf platform

    - name: Clone platform
      uses: actions/checkout@v2
      with:
        path: development/platform

    - name: Fix platform for composer
      run: |
        cd development/platform
        git fetch --prune --unshallow
        git checkout master
        git checkout -
        cd ..
        git reset --hard @

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer, prestissimo
        coverage: none

    - name: Start MySQL
      run: ./development/platform/.github/setup-db.sh mysql:5.7
    
    - name: Start Elasticsearch
      run: ./development/platform/.github/setup-es.sh elastic/elasticsearch:7.1.1

    - name: Install Shopware
      run: |
        cd development
        ./psh.phar init --DB_HOST=127.0.0.1 --DB_USER=root --DB_PASSWORD=shopware --SHOPWARE_ES_HOSTS=localhost:9200
     
    - name: Check Code
      run: |
         cd development
         php dev-ops/analyze/generate-composer.php
         php dev-ops/analyze/vendor/bin/ecs check vendor/shopware/platform/src --config vendor/shopware/platform/easy-coding-standard.yml
         php dev-ops/analyze/phpstan-config-generator.php
         for module in $(ls platform/src/); do php dev-ops/analyze/vendor/bin/psalm --config=vendor/shopware/platform/psalm.xml --threads=$(nproc) --diff --show-info=false vendor/shopware/platform/src/$module; done
         php dev-ops/analyze/vendor/bin/phpstan analyze --autoload-file=dev-ops/analyze/vendor/autoload.php --configuration platform/phpstan.neon
         php dev-ops/analyze/vendor/bin/psalm --config=vendor/shopware/platform/psalm.xml --threads=$(nproc) --show-info=false src
