name: PHP analysis

on:
    push:
        branches:
            - '6.2'
            - master
    pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DEVELOPMENT_BRANCH: 6.2

    steps:
    - name: Clone development
      run: git clone -b $DEVELOPMENT_BRANCH https://github.com/shopware/development.git && cd development && rm -rf platform

    - name: Clone platform
      uses: actions/checkout@v2
      with:
        path: development/platform

    - name: Fix platform for composer
      run: |
        cd development/platform
        git fetch --prune --unshallow
        git checkout master
        git checkout -
        cd ..
        git reset --hard @

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer, prestissimo
        coverage: none

    - name: Start MySQL
      run: ./development/platform/.github/setup-db.sh mysql:5.7

    - name: Start Elasticsearch
      run: ./development/platform/.github/setup-es.sh elastic/elasticsearch:7.1.1

    - name: Install Shopware
      run: |
        cd development
        cp platform/.github/.psh.yaml.override .
        ./psh.phar init

    - name: Check Code
      run: |
        cd development
        php dev-ops/analyze/generate-composer.php
        php dev-ops/analyze/vendor/bin/ecs check platform/src --config platform/easy-coding-standard.yml
        php dev-ops/analyze/phpstan-config-generator.php
        php dev-ops/analyze/vendor/bin/phpstan analyze --autoload-file=dev-ops/analyze/vendor/autoload.php --configuration platform/phpstan.neon --error-format gitlab | tee phpstan-report.json
        php dev-ops/analyze/vendor/bin/psalm --config=platform/psalm.xml --threads=$(nproc) --diff --diff-methods --show-info=false

